Repository rociodiaz-sistemas/StreamCoder, pull requests merged in 2024-06, with the labels that each got.

#48 Storybook animations updated
  .storybook/decorators/withTimeSlider.tsx
  .storybook/main.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/components/chat-widget/Chat.tsx
  src/components/chat-widget/chat-animations/AnimatedBackground.tsx
  src/components/storybook-tools/TimeSlider.tsx
  src/hooks/useDynamicGradient.ts
  src/stories/Chat.stories.tsx
Labels: ✨enhancement, 💅 design, 🤩 Fun

#50 Chat story bug solved
  .storybook/decorators/withDivWrapper.tsx
  src/components/chat-widget/Chat.tsx
  src/stories/Chat.stories.tsx
Labels: 🐛 bug, ✨enhancement, 🤩 Fun

#52 Time slider update
  .storybook/decorators/withTimeSlider.tsx
  src/components/chat-widget/Chat.tsx
  src/components/storybook-tools/TimeSlider.tsx
  src/hooks/useDynamicGradient.ts
  src/stories/Chat.stories.tsx
  src/stories/DynamicGradientColor.stories.tsx
  src/stories/tools/TimeSlider.tsx
Labels: ✨enhancement

#62 Money rain animation and new topbackgroundoverlay for top overlays
  src/assets/dollar-animated.svg
  src/components/chat-widget/chat-animations/Dollar.tsx
  src/components/chat-widget/chat-animations/MoneyRain.tsx
  src/components/top-background/TopBackgroundOverlay.tsx
  src/stories/BackgroundOverlay.stories.tsx
  src/stories/MoneyRain.stories.tsx
  src/stories/TopBackgroundOverlay.stories.tsx
Labels: ✨enhancement
