Repository rociodiaz-sistemas/StreamCoder, pull requests merged in 2024-07, with the labels that each got.

#64 Chat issue with emojis solved
  src/components/chat-widget/Chat.tsx
  src/components/chat-widget/chat-message/MessageContent.tsx
  src/components/chat-widget/chat-message/styles.css
Labels: 🐛 bug

#67 Chat Scroll Bug Fixed
  src/components/chat-widget/ChatPausedAlert.tsx
  src/hooks/useChatLiveModeScrolling.ts
Labels: 🐛 bug

#68 Bug space between header Fixed
  src/components/chat-widget/ChatPausedAlert.tsx
Labels: 🐛 bug

#74 Highlighter colors change dynamically
  package-lock.json
  package.json
  src/assets/highlighter.svg
  src/components/chat-widget/chat-message/usernames/HighlightedUserName.tsx
  src/store/contexts/ChatContext.tsx
  src/themes/afternoonTheme.ts
  src/themes/dayTheme.ts
  src/themes/morningTheme.ts
  src/themes/theme.ts
  vite.config.ts
Labels: ✨enhancement, 🤩 Fun

#76 Moons svgs modified
  src/assets/moons/waninggibbous.svg
  src/assets/moons/waxinggibbous.svg
Labels: ✨enhancement, 🤩 Fun

#77 Resizable bounds bigger
  src/components/chat-widget/Chat.tsx
  src/components/chat-widget/ResizableChat.tsx
Labels: ✨enhancement, 🤩 Fun

#83 Resizable border on hover
  src/components/chat-widget/ChatHeader.tsx
  src/components/chat-widget/Resizable.css
  src/components/chat-widget/ResizableChat.tsx
Labels: ✨enhancement, 🤩 Fun

#85 Saga refactor
  .eslintrc.json
  .prettierrc
  src/store/sagas/streamerbotSaga.ts
  src/store/sagas/twitchSaga.ts
  src/store/sagas/websocketSaga.ts
Labels: ⚡ refactor
